# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: serviceconnection
  value: foodalert-prakash

# Provide information for terraform's backend
- name: TerraformBackend.ResourceGroup
  value: NetworkWatcherRG
- name: TerraformBackend.StorageAccount
  value: foodalertstorageaccount
- name: TerraformBackend.ContainerName
  value: foodalert
- name: TerraformBackend.key
  value: terraform-foodalert.tfstate
- name: WorkingDir
  value: 'ashok'
stages:
- stage: 'Init'
  displayName: "Terraform Plan & Validation"
  jobs:
  - job:
    displayName: Init
    steps:
    - template: 'terraformInit.yml'
      parameters:
        subscription: $(serviceconnection)
        workingDir: '$(System.DefaultWorkingDirectory)/ashok'
        backendType: azurerm
        backendAzureRmResourceGroupName: '$(TerraformBackend.ResourceGroup)'
        backendAzureRmStorageAccountName: '$(TerraformBackend.StorageAccount)'
        backendAzureRmContainerName: '$(TerraformBackend.ContainerName)'
        backendAzureRmKey: '$(TerraformBackend.key)'
    - script: ls -ltr
